
var words = [
  ["to pull over", "se decaler"],
  ["blueprints", "plans d'architectes"],
  ["it will work out", "ca va le faire"],
  ["the staff", "l'equipe"],
  ["We have to check out", "Nous devons quitter"],
  ["Draftmen", "Dessinateurs"],
  ["I ran into a friend", "J'ai croise un ami"],
  ["Filing cabinet", "Armoire a glace"],
  ["Water cooler", "Fontaine a eau"],
  ["The key holder", "Le porte clefs"],
  ["Backstroke", "Dos crolle"],
  ["To break into", "Commettre une effraction"],
  ["Labels", "Etiquettes"],
  ["Stock", "Action"],
  ["Someone's track record", "L'historique de quelqu'un"],
  ["Broker", "Courtier"],
  ["I can't afford", "Je ne peux pas me permettre"],
  ["A rush", "Une urgence"],
  ["A first aid pack", "Une trousse de premiers secours"],
  ["Carpeting", "Moquette"],
  ["Dining car", "Wagon restaurant"],
  ["Warehouse", "Entrepot"],
  ["Conveyor belt", "Tapis roulant"],
  ["Staples", "Agrafes"],
  ["Chairman of the board", "PDG"],
  ["An invoice", "Une addition"],
  ["A bid", "Une offre"],
  ["The peak", "Le sommet"],
  ["Package", "Paquet"],
  ["Luggage", "Bagage"],
  ["Produces", "Fruits et legumes"],
  ["Bill", "Facture"],
  ["To apply", "Postuler"],
  ["Shortly", "Rapidement"],
  ["To dash out", "Quitter precipitement"],
  ["Sales", "Ventes"],
  ["Downtown", "Centre ville"],
  ["The shore", "Le rivage"],
  ["Well laid out", "Bien organise"],
  ["Transcripts", "Transcriptions"],
  ["Do you mind", "Ca te derange"],
  ["Overtime", "Heures supplementaires"],
  ["Wholesale", "Vente de gros"],
  ["Retailer", "Vente au detail"],
  ["Nail", "Clou"],
  ["To display", "Afficher"],
  ["Stationery", "Papeterie"],
  ["Socks", "Chaussettes"],
  ["To expect", "Attendre un enfant"],
  ["To be called off", "Annule"],
  ["Delayed", "Retarde"],
  ["To run out of", "Manquer de"],
  ["Supply and demand", "L'offre et la demande"],
  ["To take over", "Prendre le dessus"],
  ["Aisle", "Allee"],
  ["Greeting cards", "Cartes de voeux"]
];
