var words = [
  ["to pull over", "se décaler"],
  ["blueprints", "plans d'architectes"],
  ["it will work out", "ça va le faire"],
  ["the staff", "l'équipe"],
  ["We have to check out", "Nous devons quitter l'hôtel"],
  ["Draftmen", "Dessinateurs"],
  ["I ran into a friend", "J'ai croisé un ami"],
  ["Filing cabinet", "Armoire à glace"],
  ["Water cooler", "Fontaine à eau"],
  ["The key holder", "Le porte clef"],
  ["The backstroke", "Dos crolle"],
  ["To break into", "Commettre une effraction"],
  ["Labels", "Etiquettes"],
  ["Stock", "Action"],
  ["Someone's track record", "L'historique de quelqu'un"],
  ["Broker", "Courtier"],
  ["I can't afford", "Je ne peux pas me permettre"],
  ["A rush", "Une urgence"],
  ["A first aid pack", "Une trousse de premiers secours"],
  ["Carpeting", "Moquette"],
  ["A dining car", "Wagon restaurant"],
  ["Warehouse", "Entrepôt"],
  ["Conveyor belt", "Tapis roulant"],
  ["Staples", "Agrafes"],
  ["Chairman of the board", "PDG"],
  ["An invoice", "Une addition"],
  ["A bid", "Une offre"],
  ["The peak", "Le sommet"],
  ["Package", "Paquet"],
  ["Luggage", "Bagage"],
  ["Produce", "Fruits et légumes"],
  ["Bill", "Facture"],
  ["To apply", "Postuler"],
  ["Shortly", "Rapidement"],
  ["To dash out", "Quitter précipitamment"],
  ["Sales", "Ventes"],
  ["Downtown", "Centre ville"],
  ["The shore", "Le rivage"],
  ["Well laid out", "Bien organisé"],
  ["Transcripts", "Transcriptions"],
  ["Do you mind", "Ca te derange"],
  ["Overtime", "Heures supplémentaires"],
  ["Wholesale", "Vente de gros"],
  ["Retailer", "Vente au détail"],
  ["Nail", "Clou"],
  ["To display", "Afficher"],
  ["Stationery", "Papeterie"],
  ["Socks", "Chaussettes"],
  ["To expect", "Attendre un enfant"],
  ["To be called off", "Annulé"],
  ["Delayed", "Retardé"],
  ["To run out of", "Manquer de"],
  ["Supply and demand", "L'offre et la demande"],
  ["To take over", "Prendre le dessus"],
  ["Aisle", "Allée"],
  ["Greeting cards", "Cartes de voeux"]
];
